/**
 * iteration1.hh
 * Please do not edit this file
 */

#ifndef ITERATION1_HH
#define ITERATION1_HH

#include <iostream>
#include <iterator> // for iterators
#include <list> // for lists

void printAllItems(const std::list<int>& lst);

#endif // ITERATION1_HH
