/**
 * iteration2.hh
 * Please do not edit this file
 */

#ifndef ITERATION2_HH
#define ITERATION2_HH

#include <iostream>
#include <iterator> // for iterators
#include <list> // for lists

void printEverySecond(const std::list<int>& lst);

#endif // ITERATION2_HH
