/**
 * iteration3.hh
 * Please do not edit this file
 */

#ifndef ITERATION3_HH
#define ITERATION3_HH

#include <iostream>
#include <iterator> // for iterators
#include <list> // for lists

void printHalf(const std::list<int>& lst);

#endif // ITERATION3_HH
