/**
 * iteration3.hh
 * Please do not edit this file
 */

#ifndef ITERATION4_HH
#define ITERATION4_HH

#include <iostream>
#include <iterator> // for iterators
#include <list> // for lists

void printReverse(const std::list<int>& lst);

#endif // ITERATION4_HH
